version: 2
jobs:
  test_titanic_survived_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/titanic_model/requirements.txt
            pip install -e ./packages/titanic_model
            python packages/titanic_model/titanic_model/train_pipeline.py
            py.test -vv packages/titanic_model/tests
  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            pip install -e ./packages/titanic_model
            python packages/titanic_model/titanic_model/train_pipeline.py
            py.test -vv packages/ml_api/tests
workflows:
  version: 2
  test-all:
    jobs:
      - test_titanic_survived_model
      - test_ml_api:
          requires:
            - test_titanic_survived_model